<template><section class="settings-page"><div class="module-page-header"><div><span class="eyebrow">Cấu hình website</span><h2>Cài đặt</h2><p>Thông tin doanh nghiệp, giao diện, ngôn ngữ và lịch sử quản trị.</p></div><button v-if="activeTab!=='history'" class="primary-button" :disabled="saving" @click="save">{{saving?'Đang lưu...':'Lưu thay đổi'}}</button></div>
<div class="settings-shell"><aside class="settings-tabs"><button :class="{active:activeTab==='general'}" @click="activeTab='general'">Thông tin chung</button><button :class="{active:activeTab==='contact'}" @click="activeTab='contact'">Liên hệ & Footer</button><button :class="{active:activeTab==='theme'}" @click="activeTab='theme'">Giao diện</button><button :class="{active:activeTab==='locale'}" @click="activeTab='locale'">Ngôn ngữ</button><button :class="{active:activeTab==='history'}" @click="activeTab='history'">Lịch sử Admin</button></aside>
<div class="settings-card"><div v-if="loading&&activeTab!=='history'">Đang tải...</div><template v-else><div v-if="message" class="form-message success">{{message}}</div><div v-if="error" class="form-message error">{{error}}</div>
<div v-if="activeTab==='general'" class="settings-grid"><label><span>Tên website</span><input v-model="form.site_name"/></label><label><span>Tên công ty</span><input v-model="form.company_name"/></label><label class="full"><span>Mô tả ngắn</span><input v-model="form.tagline"/></label><label class="full"><span>Logo</span><input type="file" accept="image/*" @change="onLogo"/><img v-if="form.logo_url" class="logo-preview" :src="form.logo_url" alt="Logo"/></label></div>
<div v-else-if="activeTab==='contact'" class="settings-grid"><label><span>Số điện thoại</span><input v-model="form.phone"/></label><label><span>Email</span><input v-model="form.email" type="email"/></label><label class="full"><span>Địa chỉ</span><input v-model="form.address"/></label><label><span>Giờ mở cửa</span><input v-model="form.business_hours"/></label><label class="full"><span>Google Maps Embed URL</span><input v-model="form.map_embed_url"/></label><label><span>Facebook</span><input v-model="form.facebook_url"/></label><label><span>Instagram</span><input v-model="form.instagram_url"/></label></div>
<div v-else-if="activeTab==='theme'" class="settings-grid"><label><span>Màu chủ đạo</span><input v-model="form.primary_color" type="color"/></label><label><span>Màu phụ / nền</span><input v-model="form.secondary_color" type="color"/></label><div class="theme-preview full"><span>Preview</span><div :style="{background:form.secondary_color}"><strong :style="{color:form.primary_color}">{{form.site_name||'Bookora'}}</strong><button :style="{background:form.primary_color}">Đặt lịch</button></div></div></div>
<div v-else-if="activeTab==='locale'" class="settings-grid"><label><span>Ngôn ngữ trang Admin</span><select v-model="form.admin_language"><option value="vi">Tiếng Việt</option><option value="en">English</option></select></label></div>
<div v-else class="activity-panel"><div class="activity-toolbar"><input v-model="activitySearch" placeholder="Tìm hoạt động, admin..." @keyup.enter="loadActivities"/><select v-model="activityModule" @change="loadActivities"><option value="">Tất cả module</option><option>Bài viết</option><option>Nhân viên</option><option>Lịch đặt</option><option>Dịch vụ</option><option>Giao diện</option><option>Cài đặt</option><option>Mã giảm giá</option></select><button @click="loadActivities">Tìm</button></div><div v-if="activityLoading" class="activity-empty">Đang tải lịch sử...</div><div v-else-if="!activities.length" class="activity-empty">Chưa có hoạt động quản trị.</div><div v-else class="activity-list"><article v-for="item in activities" :key="item.id" class="activity-item"><div class="activity-icon">{{item.admin?.name?.charAt(0)||'A'}}</div><div><strong>{{item.description}}</strong><p><b>{{item.admin?.name||'Admin'}}</b> · {{item.module}}</p></div><time>{{formatDate(item.created_at)}}</time></article></div></div></template></div></div></section></template>
<script setup lang="ts">import{useSettingsView}from'./SettingsView.ts';const{activeTab,loading,saving,message,error,form,onLogo,save,activities,activityLoading,activitySearch,activityModule,loadActivities,formatDate}=useSettingsView()</script><style scoped src="./SettingsView.css"></style>
